# basic options
title: Aeorta Detection using Pix2Pix-GAN
author: Sumit Pandey 
email: sumit.ai.sci@gmail.com
description: Aeorta Detection using Pix2Pix-GAN
github_username:  Sumit-ai

# Build settings

theme: minima
